eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/
  instance:
    hostname: peer1
  server:
    enable-self-preservation: false
server:
  port: 1111
spring:
  application:
    name: server